version: '3.8'
services:
  main:
    image: main-sbt:latest
    hostname: connectfour
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - player
      - grid
    stdin_open: true
    networks:
      default:
        aliases:
          - mycontrol
  player:
    image: player-sbt:latest
    stdin_open: true
    depends_on:
      - playerdb
    networks:
      default:
        aliases:
          - myplayer
  playerdb:
    image: player-h2:latest
    networks:
      default:
        aliases:
          - player-h2
  grid:
    image: grid-sbt:latest
    stdin_open: true
    depends_on:
      - griddb
    networks:
      default:
        aliases:
          - mygrid
  griddb:
    image: grid-h2:latest
    networks:
      default:
        aliases:
          - grid-h2